import UseActiveLink from '@/hooks/UseActiveLink';
import Head from 'next/head';
import Link from 'next/link';
import React, { useState } from 'react';
import { AiFillDingtalkCircle } from 'react-icons/ai';

const MainLayout = ({ title, children }) => {
  const [currentLink, setCurrentLink] = useState('/');
  const [isLinkActive] = UseActiveLink(currentLink);
  const links = [
    {
      id: 1,
      title: 'DashBoard',
      icon: <AiFillDingtalkCircle size={30} />,
      href: '/',
    },
    {
      id: 2,
      title: 'Products',
      icon: <AiFillDingtalkCircle size={30} />,
      href: '/products',
    },
    {
      id: 3,
      title: 'Catalog',
      icon: <AiFillDingtalkCircle size={30} />,
      href: '/catalog',
    },
    {
      id: 4,
      title: 'Store',
      icon: <AiFillDingtalkCircle size={30} />,
      href: '/store',
    },
    {
      id: 5,
      title: 'Outlet',
      icon: <AiFillDingtalkCircle size={30} />,
      href: '/outlet',
    },
    {
      id: 6,
      title: 'Reports',
      icon: <AiFillDingtalkCircle size={30} />,
      href: '/reports',
    },
  ];

  console.log(isLinkActive, currentLink);
  return (
    <>
      <Head>
        <title>{title ? title : 'Sunrise Store'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="drawer drawer-mobile bg-secondary p-7">
        <input id="sideBar" type="checkbox" className="drawer-toggle" />
        <div className="drawer-content ">
          {/* <!-- Page content here --> */}
          {children}
          <label
            htmlFor="sideBar"
            className="btn btn-primary drawer-button lg:hidden"
          >
            Open drawer
          </label>
        </div>
        <div className="drawer-side">
          <label htmlFor="sideBar" className="drawer-overlay"></label>
          <div className=" py-4 w-60 bg-white rounded-lg shadow-md text-base-content">
            {/* <!-- Sidebar content here --> */}
            <Link
              href="/"
              className=" flex items-center justify-center text-primary space-x-2"
            >
              <span className="">
                <AiFillDingtalkCircle size={30} />
              </span>
              <p className="text-lg font-bold">Sunrise Store</p>
            </Link>
            <div className="mt-14">
              <p className="font-semibold text-xl text-gray-900 pl-3 pb-4">
                Overview
              </p>
              {links.slice(0, 3).map((link) => (
                <Link
                  href={link.href}
                  onClick={() => setCurrentLink(link.href)}
                  key={link?.id}
                  className={`w-full px-4 block  font-semibold text-left py-3 transition-all duration-200 ${
                    isLinkActive && currentLink === link.href
                      ? 'bg-gradient-to-r from-primary/10 to-primary/5  border-l-4 border-primary text-primary'
                      : 'bg-transparent text-gray-600'
                  }`}
                >
                  {link?.title}
                </Link>
              ))}
            </div>
            <div className="mt-5">
              <p className="font-semibold text-xl text-gray-900 pl-3 pb-4">
                Business
              </p>
              {links.slice(3, 6).map((link) => (
                <Link
                  href={link.href}
                  onClick={() => setCurrentLink(link.href)}
                  key={link?.id}
                  className={`w-full px-4 block  font-semibold text-left py-3 transition-all duration-200 ${
                    isLinkActive && currentLink === link.href
                      ? 'bg-gradient-to-r from-primary/10 to-primary/5  border-l-4 border-primary text-primary'
                      : 'bg-transparent text-gray-600'
                  }`}
                >
                  {link?.title}
                </Link>
              ))}
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default MainLayout;
