import Navbar from '@/components/Navbar/Navbar';
import { useAuth } from '@/context/AuthProvider/AuthProvider';
import UseActiveLink from '@/hooks/UseActiveLink';
import Cookies from 'js-cookie';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import React, { useState } from 'react';
import { AiFillDingtalkCircle } from 'react-icons/ai';
import { FiLogOut } from 'react-icons/fi';

const MainLayout = ({ title, children }) => {
  const [currentLink, setCurrentLink] = useState('/');
  const [isLinkActive] = UseActiveLink(currentLink);
  const { logOut } = useAuth();
  const links = [
    {
      id: 1,
      title: 'DashBoard',
      icon: <AiFillDingtalkCircle size={30} />,
      href: '/',
    },
    {
      id: 2,
      title: 'Products',
      icon: <AiFillDingtalkCircle size={30} />,
      href: `/products`,
    },
    {
      id: 3,
      title: 'Catalog',
      icon: <AiFillDingtalkCircle size={30} />,
      href: '/catalog',
    },
    {
      id: 4,
      title: 'Store',
      icon: <AiFillDingtalkCircle size={30} />,
      href: '/store',
    },
    {
      id: 5,
      title: 'Outlet',
      icon: <AiFillDingtalkCircle size={30} />,
      href: '/outlet',
    },
    {
      id: 6,
      title: 'Reports',
      icon: <AiFillDingtalkCircle size={30} />,
      href: '/reports',
    },
  ];

  console.log(isLinkActive, currentLink);
  return (
    <>
      <Head>
        <title>{title ? title : 'Sunrise Store'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="drawer drawer-mobile bg-secondary lg:p-7">
        <input id="sideBar" type="checkbox" className="drawer-toggle" />
        <div className="drawer-content ">
          {/* <!-- Page content here --> */}
          <Navbar />
          {children}
        </div>
        <div className="drawer-side">
          <label htmlFor="sideBar" className="drawer-overlay"></label>
          <div className=" py-4 w-60 bg-white rounded-lg shadow-md text-base-content relative">
            {/* <!-- Sidebar content here --> */}
            <Link
              href="/"
              className=" flex items-center px-4  text-primary space-x-2"
            >
              <span className="">
                <AiFillDingtalkCircle size={30} />
              </span>
              <p className="text-2xl font-bold">Sunrise Store</p>
            </Link>
            <div className="mt-10">
              <p className="font-semibold text-xl text-gray-900 pl-3 pb-4">
                Overview
              </p>
              {links.slice(0, 3).map((link) => (
                <Link
                  href={link.href}
                  onClick={() => setCurrentLink(link.href)}
                  key={link?.id}
                  className={`w-full px-4 block  font-semibold text-left py-3 transition-all duration-200 ${
                    isLinkActive && currentLink === link.href
                      ? 'bg-gradient-to-r from-primary/10 to-primary/5  border-l-4 border-primary text-primary'
                      : 'bg-transparent text-gray-600'
                  }`}
                >
                  {link?.title}
                </Link>
              ))}
            </div>
            <div className="mt-5">
              <p className="font-semibold text-xl text-gray-900 pl-3 pb-4">
                Business
              </p>
              {links.slice(3, 6).map((link) => (
                <Link
                  href={link.href}
                  onClick={() => setCurrentLink(link.href)}
                  key={link?.id}
                  className={`w-full px-4 block  font-semibold text-left py-3 transition-all duration-200 ${
                    isLinkActive && currentLink === link.href
                      ? 'bg-gradient-to-r from-primary/10 to-primary/5  border-l-4 border-primary text-primary'
                      : 'bg-transparent text-gray-600'
                  }`}
                >
                  {link?.title}
                </Link>
              ))}
            </div>
            <div className="absolute bottom-3 w-full px-4">
              <div
                onClick={logOut}
                className="flex items-center justify-center mt-16 btn btn-primary text-white w-full space-x-1 px-5"
              >
                <span className="bg-transparent w-8 h-8 text-white  rounded-full flex items-center justify-center">
                  <FiLogOut size={22} />
                </span>
                <h4 className="font-bold">LogOut</h4>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default MainLayout;
